In [2]:
pip install torch torchvision torchaudio

  Using cached torch-2.8.0-cp313-cp313-win_amd64.whl.metadata (30 kB)
   ---------------------------------------- 0.0/241.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/241.3 MB ? eta -:--:--
   ---------------------------------------- 0.8/241.3 MB 2.0 MB/s eta 0:02:02
   ---------------------------------------- 1.0/241.3 MB 2.1 MB/s eta 0:01:54
   ---------------------------------------- 1.8/241.3 MB 2.4 MB/s eta 0:01:41
   ---------------------------------------- 2.4/241.3 MB 2.3 MB/s eta 0:01:44
   ---------------------------------------- 2.9/241.3 MB 2.4 MB/s eta 0:01:39
    --------------------------------------- 3.4/241.3 MB 2.4 MB/s eta 0:01:39
    --------------------------------------- 3.4/241.3 MB 2.4 MB/s eta 0:01:39
    --------------------------------------- 3.7/241.3 MB 2.1 MB/s eta 0:01:51
    --------------------------------------- 4.2/241.3 MB 2.0 MB/s eta 0:01:57
    --------------------------------------- 4.5/241.3 MB 2.0 MB/s eta 0:02:02
    ----

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.8.0+cpu


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0]

tensor([7, 8])

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
ten = torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]]])
ten

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
ten.ndim

3

In [14]:
ten.shape

torch.Size([1, 3, 3])

In [15]:
ran = torch.rand(3,4)
ran

tensor([[0.8030, 0.3203, 0.3702, 0.3925],
        [0.0809, 0.1800, 0.6665, 0.9294],
        [0.2775, 0.7700, 0.6141, 0.0757]])

In [16]:
torch.rand(3,3)

tensor([[0.0443, 0.1083, 0.6298],
        [0.0856, 0.6633, 0.7078],
        [0.3965, 0.7516, 0.6441]])

In [17]:
torch.zeros(size=(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
one =torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
one.dtype

torch.float32

In [20]:
torch.range(0,10)

C:\Users\Sahil\AppData\Local\Temp\ipykernel_8860\497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
one_2_ten = torch.arange(start=1,end=11,step=1)
one_2_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
ten_zero = torch.zeros_like(input = one_2_ten)

In [23]:
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [25]:
a+10

tensor([11, 12, 13])

In [26]:
a*10

tensor([10, 20, 30])

In [27]:
a-10

tensor([-9, -8, -7])

In [28]:
a.mul(10)

tensor([10, 20, 30])

In [29]:
a.add(10)

tensor([11, 12, 13])

In [30]:
a.sub(1)

tensor([0, 1, 2])

In [31]:
torch.mul(a,10)

tensor([10, 20, 30])

In [32]:
torch.add(a,10)

tensor([11, 12, 13])

In [33]:
torch.sub(a,1)

tensor([0, 1, 2])

matrix multi
* (3,2) @ (3,2) not work


* (3,2)@ (2,3) will work

In [34]:
mat1 = torch.rand(3, 2)
mat2 = torch.rand(3, 3)
result = torch.matmul(mat1.T, mat2)
print(result.shape)

torch.Size([2, 3])


In [35]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[1.2735, 0.7330],
        [0.7082, 0.5277]])

In [36]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.1750, 0.1632, 0.1802],
        [0.2567, 0.3138, 0.1918],
        [0.0544, 0.0090, 0.0965]])

In [37]:
# tensor aggregation (max . min , sum , mean etc)

In [38]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
torch.min(x)

tensor(0)

In [40]:
x.min()

tensor(0)

In [41]:
torch.max(x)

tensor(90)

In [42]:
x.max()

tensor(90)

In [43]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [44]:
x.type(torch.float32).mean()

tensor(45.)

In [45]:
x.sum()

tensor(450)

In [46]:
x.argmax()

tensor(9)

In [47]:
x[9]

tensor(90)

In [48]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
x_reshape = x.reshape(1,9)

In [50]:
x_reshape,x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
z[:0]= 5
z , x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [53]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [54]:
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
x_reshape.shape

torch.Size([1, 9])

In [56]:
x_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])